"""evaluations table + enum

Revision ID: 7467d1ab84e4
Revises: 06f23a279849
Create Date: 2026-05-25 02:00:33.430136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7467d1ab84e4'
down_revision: Union[str, None] = '06f23a279849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'running', 'complete', 'failed', name='evaluation_status'), nullable=False),
    sa.Column('backend', sa.String(length=32), nullable=True),
    sa.Column('cv_score', sa.Integer(), nullable=True),
    sa.Column('cover_letter_score', sa.Integer(), nullable=True),
    sa.Column('job_match_score', sa.Integer(), nullable=True),
    sa.Column('ats_score', sa.Integer(), nullable=True),
    sa.Column('competitiveness_score', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('missing_keywords', sa.JSON(), nullable=True),
    sa.Column('missing_skills', sa.JSON(), nullable=True),
    sa.Column('weak_statements', sa.JSON(), nullable=True),
    sa.Column('company_alignment_notes', sa.JSON(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('contract_tx_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_evaluations_application_id_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluations')),
    sa.UniqueConstraint('application_id', name='uq_evaluations_application_id')
    )
    op.create_index(op.f('ix_evaluations_application_id'), 'evaluations', ['application_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluations_application_id'), table_name='evaluations')
    op.drop_table('evaluations')
    # ### end Alembic commands ###
