"""user wallet columns

Revision ID: b74a37017d63
Revises: 1851cfcda4db
Create Date: 2026-05-25 13:07:05.420843

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b74a37017d63'
down_revision: str | None = '1851cfcda4db'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('wallet_address', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('encrypted_private_key', sa.String(length=512), nullable=True))
    op.create_index(op.f('ix_users_wallet_address'), 'users', ['wallet_address'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_wallet_address'), table_name='users')
    op.drop_column('users', 'encrypted_private_key')
    op.drop_column('users', 'wallet_address')
    # ### end Alembic commands ###
